title: Crisis and Opportunity Books
description: Digital reprints of Harlem Renaissance classics

remote_theme: mmistakes/minimal-mistakes

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  books:
    output: true
    permalink: /:collection/:name/
    
include:
  - _pages
