title: Crisis and Opportunity Books
description: Digital reprints of Harlem Renaissance classics

remote_theme: mmistakes/minimal-mistakes

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  releases:
    output: true
    permalink: /:collection/:name/

exclude:
  - books
  
# Default configuration for books
defaults:
  - scope:
      path: "_releases"
    values:
      layout: book

# Pagination (Optional for listing books)
paginate: 5 # Number of books per page
paginate_path: "/page:num/"