title: Crisis and Opportunity Books
description: Digital reprints of Harlem Renaissance classics

#remote_theme: mmistakes/minimal-mistakes
remote_theme: pages-themes/minimal@v0.2.0

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  books:
    output: true
    permalink: /:collection/:name/
    
include:
  - _pages

# Add these to your existing config
paginate: 15  # Number of posts per page
paginate_path: /page:num/
future: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
      show_date: true
      excerpt: false
      classes: header-only